-   id: goimports-reviser
    name: goimports-reviser
    description: Sort go imports.
    entry: goimports-reviser
    language: go
    types: [golang]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
